language: python
python:
  - "2.7"

sudo: false

env:
  - PLATFORMIO_CI_SRC=Main/Main.ino

install:
  - pip install  -U platformio
  - platformio update

script:
  - platformio run

notifications:
  slack:
    on_success: always
    on_failure: always
